/**
 * Created by harekam on 23/10/15.
 */
var Twitter = require('twitter');
var config = require('./../config/index');
var DAO = require('./../dao/dao');
var twitterAuth = config.twitterConfig.auth;
var log4js = require('log4js');
var logger = log4js.getLogger('[TWITTER_MANAGER]');
var util = require('pure-util');
var models = require('./../models/index');
var async = require('async');
var testjson = [{
    created_at: 'Thu Oct 22 11:15:01 +0000 2015',
    id: 657153178211885000,
    id_str: '657153178211885056',
    text: 'Christmas decoration in Oxford street • #london #landscape #uk #exteriordesign @ Oxford Circus https://t.co/qyeVkIW0QW',
    source: '<a href="http://instagram.com" rel="nofollow">Instagram</a>',
    truncated: false,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
        id: 353312817,
        id_str: '353312817',
        name: 'Margaux de Matteis',
        screen_name: 'MDMatteis',
        location: 'Londres, Angleterre',
        url: 'http://mdmatteis.tumblr.com',
        description: 'Communication student | 21 yo | Fashion - Design - Deco | London | instagram & pinterest : margauxdmts',
        protected: false,
        verified: false,
        followers_count: 123,
        friends_count: 122,
        listed_count: 14,
        favourites_count: 28,
        statuses_count: 2034,
        created_at: 'Thu Aug 11 21:49:42 +0000 2011',
        utc_offset: 10800,
        time_zone: 'Athens',
        geo_enabled: true,
        lang: 'fr',
        contributors_enabled: false,
        is_translator: false,
        profile_background_color: '4A4959',
        profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/543458073549869056/-egVaq1N.jpeg',
        profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/543458073549869056/-egVaq1N.jpeg',
        profile_background_tile: true,
        profile_link_color: '0099CC',
        profile_sidebar_border_color: 'FFFFFF',
        profile_sidebar_fill_color: '252429',
        profile_text_color: '666666',
        profile_use_background_image: true,
        profile_image_url: 'http://pbs.twimg.com/profile_images/378800000866568517/hdHMKQkx_normal.jpeg',
        profile_image_url_https: 'https://pbs.twimg.com/profile_images/378800000866568517/hdHMKQkx_normal.jpeg',
        profile_banner_url: 'https://pbs.twimg.com/profile_banners/353312817/1425333714',
        default_profile: false,
        default_profile_image: false,
        following: null,
        follow_request_sent: null,
        notifications: null
    },
    geo: {type: 'Point', coordinates: [51.5153, -0.142]},
    coordinates: {type: 'Point', coordinates: [-0.142, 51.5153]},
    place: {
        id: '56c45474148ca4da',
        url: 'https://api.twitter.com/1.1/geo/id/56c45474148ca4da.json',
        place_type: 'city',
        name: 'Paddington',
        full_name: 'Paddington, London',
        country_code: 'GB',
        country: 'United Kingdom',
        bounding_box: {type: 'Polygon', coordinates: [Object]},
        attributes: {}
    },
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    entities: {
        hashtags: [[Object], [Object], [Object], [Object]],
        urls: [[Object]],
        user_mentions: [],
        symbols: []
    },
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    filter_level: 'low',
    lang: 'en',
    timestamp_ms: '1445512501658'
},
    {
        created_at: 'Thu Oct 22 11:15:05 +0000 2015',
        id: 657153194993303600,
        id_str: '657153194993303552',
        text: 'I\'m at Student Services in Ormskirk https://t.co/Uqo4M73yVd',
        source: '<a href="http://foursquare.com" rel="nofollow">Foursquare</a>',
        truncated: false,
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: {
            id: 488127611,
            id_str: '488127611',
            name: 'Hsin',
            screen_name: 'onlysepia',
            location: 'Liverpool, England',
            url: 'http://Instagram.com/luhsin',
            description: 'Experience seeker | 2nd-year Marketing student at UoL',
            protected: false,
            verified: false,
            followers_count: 182,
            friends_count: 120,
            listed_count: 7,
            favourites_count: 688,
            statuses_count: 43554,
            created_at: 'Fri Feb 10 03:32:48 +0000 2012',
            utc_offset: 3600,
            time_zone: 'London',
            geo_enabled: true,
            lang: 'en',
            contributors_enabled: false,
            is_translator: false,
            profile_background_color: 'C0DEED',
            profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
            profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
            profile_background_tile: false,
            profile_link_color: '0084B4',
            profile_sidebar_border_color: 'C0DEED',
            profile_sidebar_fill_color: 'DDEEF6',
            profile_text_color: '333333',
            profile_use_background_image: true,
            profile_image_url: 'http://pbs.twimg.com/profile_images/641580939064250368/5pX6PZhj_normal.jpg',
            profile_image_url_https: 'https://pbs.twimg.com/profile_images/641580939064250368/5pX6PZhj_normal.jpg',
            profile_banner_url: 'https://pbs.twimg.com/profile_banners/488127611/1442472063',
            default_profile: true,
            default_profile_image: false,
            following: null,
            follow_request_sent: null,
            notifications: null
        },
        geo: {type: 'Point', coordinates: [53.560194, -2.874609]},
        coordinates: {type: 'Point', coordinates: [-2.874609, 53.560194]},
        place: {
            id: '01d711761615d783',
            url: 'https://api.twitter.com/1.1/geo/id/01d711761615d783.json',
            place_type: 'city',
            name: 'Ormskirk',
            full_name: 'Ormskirk, England',
            country_code: 'GB',
            country: 'United Kingdom',
            bounding_box: {type: 'Polygon', coordinates: [Object]},
            attributes: {}
        },
        contributors: null,
        is_quote_status: false,
        retweet_count: 0,
        favorite_count: 0,
        entities: {
            hashtags: [],
            urls: [[Object]],
            user_mentions: [],
            symbols: []
        },
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        filter_level: 'low',
        lang: 'en',
        timestamp_ms: '1445512505659'
    },
    {
        created_at: 'Thu Oct 22 11:15:18 +0000 2015',
        id: 657153249527636000,
        id_str: '657153249527635968',
        text: 'I\'m at Walmart Neighborhood Grocery in Waxhaw, NC https://t.co/1QU6Pu0Zdz',
        source: '<a href="http://foursquare.com" rel="nofollow">Foursquare</a>',
        truncated: false,
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: {
            id: 15519502,
            id_str: '15519502',
            name: 'G H Holt Photography',
            screen_name: 'ghholt',
            location: 'Waxhaw, NC',
            url: 'http://about.me/ghholtphotography',
            description: 'I am a Waxhaw, NC based portrait photographer with over 40 years experience. I am a member of the Professional Photographers of America.',
            protected: false,
            verified: false,
            followers_count: 308,
            friends_count: 352,
            listed_count: 20,
            favourites_count: 19,
            statuses_count: 6699,
            created_at: 'Mon Jul 21 19:32:11 +0000 2008',
            utc_offset: -10800,
            time_zone: 'Atlantic Time (Canada)',
            geo_enabled: true,
            lang: 'en',
            contributors_enabled: false,
            is_translator: false,
            profile_background_color: 'C0DEED',
            profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/88793024/3924461249_21c878f699_b.jpg',
            profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/88793024/3924461249_21c878f699_b.jpg',
            profile_background_tile: false,
            profile_link_color: '0084B4',
            profile_sidebar_border_color: 'C0DEED',
            profile_sidebar_fill_color: 'DDEEF6',
            profile_text_color: '333333',
            profile_use_background_image: true,
            profile_image_url: 'http://pbs.twimg.com/profile_images/660083754/4116987559_1c2cb93ba0_t_normal.jpg',
            profile_image_url_https: 'https://pbs.twimg.com/profile_images/660083754/4116987559_1c2cb93ba0_t_normal.jpg',
            default_profile: false,
            default_profile_image: false,
            following: null,
            follow_request_sent: null,
            notifications: null
        },
        geo: {type: 'Point', coordinates: [34.95831849, -80.75663809]},
        coordinates: {type: 'Point', coordinates: [-80.75663809, 34.95831849]},
        place: {
            id: '3b98b02fba3f9753',
            url: 'https://api.twitter.com/1.1/geo/id/3b98b02fba3f9753.json',
            place_type: 'admin',
            name: 'North Carolina',
            full_name: 'North Carolina, USA',
            country_code: 'US',
            country: 'United States',
            bounding_box: {type: 'Polygon', coordinates: [Object]},
            attributes: {}
        },
        contributors: null,
        is_quote_status: false,
        retweet_count: 0,
        favorite_count: 0,
        entities: {
            hashtags: [],
            urls: [[Object]],
            user_mentions: [],
            symbols: []
        },
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        filter_level: 'low',
        lang: 'en',
        timestamp_ms: '1445512518661'
    }, {
        created_at: 'Thu Oct 22 11:15:19 +0000 2015',
        id: 657153253734490100,
        id_str: '657153253734490112',
        text: 'Holding tight to my beer #beer #drinks @ The Bee https://t.co/IHh86k2rXo',
        source: '<a href="http://instagram.com" rel="nofollow">Instagram</a>',
        truncated: false,
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: {
            id: 37883075,
            id_str: '37883075',
            name: 'Tracy Too',
            screen_name: 'TracyToo_',
            location: 'Malaysia',
            url: null,
            description: 'Eat, Pray & ❤️ Lee MinHo',
            protected: false,
            verified: false,
            followers_count: 67,
            friends_count: 75,
            listed_count: 4,
            favourites_count: 171,
            statuses_count: 4769,
            created_at: 'Tue May 05 08:05:56 +0000 2009',
            utc_offset: 28800,
            time_zone: 'Kuala Lumpur',
            geo_enabled: true,
            lang: 'en',
            contributors_enabled: false,
            is_translator: false,
            profile_background_color: 'EBEBEB',
            profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/125172441/eclipse.jpg',
            profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/125172441/eclipse.jpg',
            profile_background_tile: true,
            profile_link_color: '990000',
            profile_sidebar_border_color: 'DFDFDF',
            profile_sidebar_fill_color: 'F3F3F3',
            profile_text_color: '333333',
            profile_use_background_image: true,
            profile_image_url: 'http://pbs.twimg.com/profile_images/602854314260893698/CZunIER__normal.jpg',
            profile_image_url_https: 'https://pbs.twimg.com/profile_images/602854314260893698/CZunIER__normal.jpg',
            profile_banner_url: 'https://pbs.twimg.com/profile_banners/37883075/1432566643',
            default_profile: false,
            default_profile_image: false,
            following: null,
            follow_request_sent: null,
            notifications: null
        },
        geo: {type: 'Point', coordinates: [3.17093952, 101.66760756]},
        coordinates: {type: 'Point', coordinates: [101.66760756, 3.17093952]},
        place: {
            id: 'e7a411bac68f57b1',
            url: 'https://api.twitter.com/1.1/geo/id/e7a411bac68f57b1.json',
            place_type: 'admin',
            name: 'Kuala Lumpur',
            full_name: 'Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur',
            country_code: 'MY',
            country: 'Malaysia',
            bounding_box: {type: 'Polygon', coordinates: [Object]},
            attributes: {}
        },
        contributors: null,
        is_quote_status: false,
        retweet_count: 0,
        favorite_count: 0,
        entities: {
            hashtags: [[Object], [Object]],
            urls: [[Object]],
            user_mentions: [],
            symbols: []
        },
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        filter_level: 'low',
        lang: 'en',
        timestamp_ms: '1445512519664'
    }, {
        created_at: 'Thu Oct 22 11:16:20 +0000 2015',
        id: 657153509595480000,
        id_str: '657153509595480064',
        text: 'I\'m reading Romans 5:8 https://t.co/CIRnkQA0WY via @Vyrso https://t.co/pQSRdaDPZ9',
        source: '<a href="https://twitter.com/download/android" rel="nofollow">Twitter for Android Tablets</a>',
        truncated: false,
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: {
            id: 3359090535,
            id_str: '3359090535',
            name: 'Erroll W. Thompson',
            screen_name: 'erroll_T',
            location: 'Fountainhead-Orchard Hills, MD',
            url: null,
            description: null,
            protected: false,
            verified: false,
            followers_count: 12,
            friends_count: 56,
            listed_count: 0,
            favourites_count: 6,
            statuses_count: 368,
            created_at: 'Sat Jul 04 18:49:36 +0000 2015',
            utc_offset: null,
            time_zone: null,
            geo_enabled: true,
            lang: 'en',
            contributors_enabled: false,
            is_translator: false,
            profile_background_color: 'C0DEED',
            profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
            profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
            profile_background_tile: false,
            profile_link_color: '0084B4',
            profile_sidebar_border_color: 'C0DEED',
            profile_sidebar_fill_color: 'DDEEF6',
            profile_text_color: '333333',
            profile_use_background_image: true,
            profile_image_url: 'http://pbs.twimg.com/profile_images/635101241488445441/W9oWH1i4_normal.jpg',
            profile_image_url_https: 'https://pbs.twimg.com/profile_images/635101241488445441/W9oWH1i4_normal.jpg',
            default_profile: true,
            default_profile_image: false,
            following: null,
            follow_request_sent: null,
            notifications: null
        },
        geo: {type: 'Point', coordinates: [39.6909871, -77.72439158]},
        coordinates: {type: 'Point', coordinates: [-77.72439158, 39.6909871]},
        place: {
            id: 'f9abee4b8cdfec3d',
            url: 'https://api.twitter.com/1.1/geo/id/f9abee4b8cdfec3d.json',
            place_type: 'city',
            name: 'Fountainhead-Orchard Hills',
            full_name: 'Fountainhead-Orchard Hills, MD',
            country_code: 'US',
            country: 'United States',
            bounding_box: {type: 'Polygon', coordinates: [Object]},
            attributes: {}
        },
        contributors: null,
        is_quote_status: false,
        retweet_count: 0,
        favorite_count: 0,
        entities: {
            hashtags: [],
            urls: [[Object]],
            user_mentions: [[Object]],
            symbols: [],
            media: [[Object]]
        },
        extended_entities: {media: [[Object]]},
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        filter_level: 'low',
        lang: 'en',
        timestamp_ms: '1445512580666'
    }, {
        created_at: 'Thu Oct 22 11:16:39 +0000 2015',
        id: 657153589274505200,
        id_str: '657153589274505220',
        text: 'When you try to study hard lying on your bed.... aigooo aigoo....Suddenly something comes to your mind https://t.co/adyr0xy0gb',
        source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
        truncated: false,
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: {
            id: 2525063750,
            id_str: '2525063750',
            name: 'Zaema Khan',
            screen_name: 'ZaemaKhan',
            location: 'Seoul, Korea',
            url: null,
            description: 'PhD Scholar,\nActive,planfull,generous,angry young women ,sincere,sensitive,naughty & loving. I dream & imagine, hope, believe & have faith with my heart.',
            protected: false,
            verified: false,
            followers_count: 30,
            friends_count: 22,
            listed_count: 0,
            favourites_count: 37,
            statuses_count: 39,
            created_at: 'Mon May 26 13:40:40 +0000 2014',
            utc_offset: 18000,
            time_zone: 'Islamabad',
            geo_enabled: true,
            lang: 'en',
            contributors_enabled: false,
            is_translator: false,
            profile_background_color: '642D8B',
            profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/471305315460202496/XZEHlXiY.jpeg',
            profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/471305315460202496/XZEHlXiY.jpeg',
            profile_background_tile: true,
            profile_link_color: 'FA743E',
            profile_sidebar_border_color: '000000',
            profile_sidebar_fill_color: 'DDEEF6',
            profile_text_color: '333333',
            profile_use_background_image: false,
            profile_image_url: 'http://pbs.twimg.com/profile_images/656464692156563456/SvMj_3f7_normal.jpg',
            profile_image_url_https: 'https://pbs.twimg.com/profile_images/656464692156563456/SvMj_3f7_normal.jpg',
            profile_banner_url: 'https://pbs.twimg.com/profile_banners/2525063750/1445348352',
            default_profile: false,
            default_profile_image: false,
            following: null,
            follow_request_sent: null,
            notifications: null
        },
        geo: {type: 'Point', coordinates: [35.1399339, 126.9280954]},
        coordinates: {type: 'Point', coordinates: [126.9280954, 35.1399339]},
        place: {
            id: '07d403fda5cb90c2',
            url: 'https://api.twitter.com/1.1/geo/id/07d403fda5cb90c2.json',
            place_type: 'admin',
            name: 'Seoul',
            full_name: 'Seoul, Republic of Korea',
            country_code: 'KR',
            country: '대한민국',
            bounding_box: {type: 'Polygon', coordinates: [Object]},
            attributes: {}
        },
        contributors: null,
        is_quote_status: false,
        retweet_count: 0,
        favorite_count: 0,
        entities: {
            hashtags: [],
            urls: [],
            user_mentions: [],
            symbols: [],
            media: [[Object]]
        },
        extended_entities: {media: [[Object]]},
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        filter_level: 'low',
        lang: 'en',
        timestamp_ms: '1445512599663'
    }, {
        created_at: 'Thu Oct 22 11:16:43 +0000 2015',
        id: 657153606060240900,
        id_str: '657153606060240896',
        text: 'Sticky cinnamon 👊🏼 (@ Starbucks in Guiguinto, Bulacan) https://t.co/auMnjsnMjC',
        source: '<a href="http://foursquare.com" rel="nofollow">Foursquare</a>',
        truncated: false,
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: {
            id: 93001267,
            id_str: '93001267',
            name: 'Donnaleen Lao',
            screen_name: 'YatsLao_Tzu',
            location: 'Caloocan City',
            url: 'http://yatslaotzu.tumblr.com',
            description: 'ART never comes from happiness',
            protected: false,
            verified: false,
            followers_count: 265,
            friends_count: 263,
            listed_count: 3,
            favourites_count: 10350,
            statuses_count: 15462,
            created_at: 'Fri Nov 27 16:37:42 +0000 2009',
            utc_offset: 28800,
            time_zone: 'Beijing',
            geo_enabled: true,
            lang: 'en',
            contributors_enabled: false,
            is_translator: false,
            profile_background_color: '709397',
            profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/862341482/b7702fff10e9c09be924414d629d4180.jpeg',
            profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/862341482/b7702fff10e9c09be924414d629d4180.jpeg',
            profile_background_tile: true,
            profile_link_color: 'FF3300',
            profile_sidebar_border_color: 'FFFFFF',
            profile_sidebar_fill_color: 'A0C5C7',
            profile_text_color: '333333',
            profile_use_background_image: true,
            profile_image_url: 'http://pbs.twimg.com/profile_images/653428684133535744/3T7ahcBW_normal.jpg',
            profile_image_url_https: 'https://pbs.twimg.com/profile_images/653428684133535744/3T7ahcBW_normal.jpg',
            profile_banner_url: 'https://pbs.twimg.com/profile_banners/93001267/1441236141',
            default_profile: false,
            default_profile_image: false,
            following: null,
            follow_request_sent: null,
            notifications: null
        },
        geo: {type: 'Point', coordinates: [14.85070385, 120.87519765]},
        coordinates: {type: 'Point', coordinates: [120.87519765, 14.85070385]},
        place: {
            id: '00059906035ff832',
            url: 'https://api.twitter.com/1.1/geo/id/00059906035ff832.json',
            place_type: 'city',
            name: 'Guiguinto',
            full_name: 'Guiguinto, Central Luzon',
            country_code: 'PH',
            country: 'Republika ng Pilipinas',
            bounding_box: {type: 'Polygon', coordinates: [Object]},
            attributes: {}
        },
        contributors: null,
        is_quote_status: false,
        retweet_count: 0,
        favorite_count: 0,
        entities: {
            hashtags: [],
            urls: [[Object]],
            user_mentions: [],
            symbols: []
        },
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        filter_level: 'low',
        lang: 'en',
        timestamp_ms: '1445512603665'
    }
];

function enterData(tweet, callback) {
    var body = {
        createdAt: new Date(tweet.created_at),
        //tweetId: tweet.id,
        text: tweet.text,
        source: fetchSourceName(tweet.source),
        categories: util.isEmpty(tweet.entities) ? [] : tweet.entities.hashtags,
        entities: util.isEmpty(tweet.entities) ? [] : tweet.entities.user_mentions,
        geo: tweet.geo,
        coordinates: tweet.coordinates,
        place: tweet.place
    };
    if (!util.isEmpty(tweet.user)) {
        var userDetails = tweet.user;
        body.user = {
            id: userDetails.id,
            name: userDetails.name,
            screenName: userDetails.screen_name,
            followersCount: userDetails.followers_count,
            friendsCount: userDetails.friends_count,
            statusesCount: userDetails.statuses_count,
            favouritesCount: userDetails.favourites_count,
            createdAt: new Date(userDetails.created_at)
        }
    }
    var options = {
        _index: models.leadsModel.index,
        _type: models.leadsModel.type,
        _id: tweet.id
    };
    logger.trace(tweet.text);
    DAO.setData(options, body, callback);
}

function upload(tweets, callbackParent) {

    var taskToRunInParallel = [];
    tweets.forEach(function (dataObj) {
        taskToRunInParallel.push((function (dataObj) {
            return function (embeddedCB) {
                enterData(dataObj, embeddedCB);
            }

        })(dataObj));
    });
    async.parallel(taskToRunInParallel, function (error) {
        if (error)
            return callbackParent(error);
        return callbackParent(null);
    });
}
upload(testjson, function (err) {
    if (err)
        logger.error(err);
});
function fetchSourceName(source) {
    var sourceName = source.substring(source.indexOf('>') + 1, source.indexOf('</a>'));
    sourceName = sourceName.toUpperCase();
    var deviceIndex = sourceName.indexOf('TWITTER FOR');
    if (deviceIndex !== -1) {
        sourceName = sourceName.substring(deviceIndex + 12);
    }
    return sourceName;
}
